sonar.projectKey=marine-toxicity-devops
sonar.projectName=Marine Toxicity DevOps
sonar.projectVersion=lab4

sonar.sources=backend/app,frontend/src
sonar.tests=backend/app/tests,frontend/src
sonar.test.inclusions=backend/app/tests/**/*.py,frontend/src/**/*.test.jsx,frontend/src/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.egg-info/**,**/__pycache__/**
sonar.coverage.exclusions=backend/app/tests/**,frontend/src/**/*.test.jsx,frontend/src/**/*.test.js,frontend/src/test/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
