apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: marine-toxicity
  namespace: argocd
spec:
  description: Marine toxicity lab environments
  sourceRepos:
    - https://github.com/FooolyHARD/DevOps.git
  destinations:
    - namespace: lab3
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: security
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
