apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marine-toxicity-security
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: marine-toxicity
  source:
    repoURL: https://github.com/FooolyHARD/DevOps.git
    targetRevision: lab4
    path: lab4/k8s/security
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
